# Setup
title:        PersonalWAB
tagline:      (WWW'25) Large Language Models Empowered Personalized Web Agents
baseurl:      "/PersonalWAB"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Hongru Cai
  url:        https://hongrucai.github.io/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown